[package]
name = "neutrondb"
version = "0.9.1"
edition = "2018"
license = "MIT"
description = "Rust implementation of NeutronDB, a Log-Structured Merge-tree Key-Value Store serialized as Stellar Notation Objects."
repository = "https://github.com/seg-software/neutrondb-rs"
readme = "README.md"

[dependencies]
stellar-notation = "0.9.3"
blake3 = "1.0.0"
sha2 = "0.9.5"
sha3 = "0.9.1"
